services:
  postgresql:
    image: postgres:17.5-bookworm
    container_name: postgresql
    env_file: .env
    networks:
      - etelecom_voip_network
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672    # AMQP
      - 15672:15672  # Management UI
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - etelecom_voip_network
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
networks:
  etelecom_voip_network:
    external: true
    driver: bridge
# docker network create --subnet=172.22.0.0/16 etelecom_voip_network