services:
  cdr-ingestor:
    image: xuanthang9860/softswitch-cdr-ingestor:v1.0.0
    container_name: cdr-ingestor
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 8081:8080
    volumes:
      - ./config:/app/config
      - ./log:/app/log
    networks:
      -  etelecom_voip_network
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    

networks:
  etelecom_voip_network:
    external: true
    driver: bridge
# docker network create --subnet=172.22.0.0/16 etelecom_voip_network